### ISSUE TITLE
Add option to generate the html with a custom style

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#11]
It would be nice to have a command line to generate the apidoc with a custom stylesheet
Maybe a bit like https://github.com/danielgtaylor/aglio#custom-colors--style does it, though not all those features there are needed

**Comment by SMillerDev** [comment]
This already has some working parts: https://github.com/SMillerDev/phpdraft/wiki/Templates
Just doesn't have any other default styles or any testing done to it.
