### ISSUE TITLE
Parameters enum mess up the example URI

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#138]
See last example of https://apiblueprint.org/documentation/specification.html#def-uriparameters-section

```
+ Parameters
    + id (enum[string])

        Id of a Post

        + Members
            + `A`
            + `B`
            + `C`
```

Some HTML generated from this section ends up being present escaped in the example URI

**Comment by SMillerDev** [comment]
I believe this is fixed in 2.3.0
