### ISSUE TITLE
Detailed requests display

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#14]
Currently, only the body of the requests are displayed.
We would need to have the individual fields displayed with their full description (type, required,...)

**Comment by SMillerDev** [comment]
You're referring to GET parameters here?

**Comment by tardypad** [comment]
No I'm talking about the what API Blueprint calls `Attributes`.
I don't have example with GET parameters so I'm not sure how they would be displayed.
But in the end each field, whether from `Attributes` or `Parameters`, should be listed with their full description
