### ISSUE TITLE
Instructions to build the tool

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#17]
Just a small suggestion
Maybe you could add a small section in the README to explain how to build this tool
At least put that the build is done using `ant` and that there is a dependency on [phpab](https://github.com/theseer/Autoload).
And then maybe display the main build command `ant phar` .
I think the rest may already be explained good enough in the build.xml file.

**Comment by tardypad** [comment]
I guess they are other dependencies / setup needed there
When trying to use the phar file I've just built, the HTML generated contains only an error
`PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in phar`

**Comment by SMillerDev** [comment]
Nope, that's just me badly naming classes. Should be fixed now.
