### ISSUE TITLE
Missing or wrong display of some example values

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#21]
In some cases, the example values don't get displayed:
```+ arrival : `false` ```
```+ description  : `_Electronics_` ```
```+ description  : `*Electronics*` ```

or the display is wrong:
```hideOnMap    : `true` ``` result in `1` being shown

**Comment by SMillerDev** [comment]
Lovely, you discovered a type of defaults.... Should be fixed in 1.4

**Comment by tardypad** [comment]
As far as I can see, this is not correctly fixed
`_Electronics_` is now displayed as 'Electronics' only
Not sure also why `false` is displayed capitalized as FALSE

**Comment by SMillerDev** [comment]
`Electronics` is just the way drafter returns the data. As for FALSE, I'll make that lowercase in the next update
