### ISSUE TITLE
Ordering of data structures

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#22]
Currently the groups and data structures are ordered in the apidoc in the order they were included in the apib file.
While I think this is fine for the groups part, since we generally want to order them manually for some diverse reasons, it is a bit inconvenient for the data structures when we want to reach a particular one.
I think it would make sense to order them alphabetically by their name.

**Comment by SMillerDev** [comment]
Don't think this would be a real benefit over manually sorting them. They're handled in the way they are in the APIB and nothing more.

I could make a button to sort them but I personally don't see the benefit @tardypad

**Comment by SMillerDev** [comment]
Decided on making it a compile flag

--sort=All|Webservices|Structures|__None__
