### ISSUE TITLE
Display of special characters

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#24]
There seems to be some troubles with the display of special characters
a description such as `Temperature in Fahrenheit (°F)`
gets displayed as `Temperature in Fahrenheit (Â°F)`

**Comment by SMillerDev** [comment]
STOP RUNNING INTO SYSTEM LIMITATIONS DAMNED

**Comment by tardypad** [comment]
HAHAHA

**Comment by tardypad** [comment]
Is this already a problem coming from the underlying parser?
