### ISSUE TITLE
link usage problem in member description

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#26]
The description of members is now parsed as Markdown and we can then put links in there.
Unfortunately in some cases it breaks the parsing.

`+ logoId (string, required)  - [Asset ID](#object-contentful__asset) of the airlines logo`
would be correctly parsed and displayed with a link
But
`+ logo_Id (string, required)  - [Asset ID](#object-contentful__asset) of the airlines logo`
would be wrongly parsed and this whole text would be displayed as the member name!

I believe this is because there is the character `_` in both the member name and the description
I think this issue needs to be reported to the parser

On the other side, is it maybe possible to generate internal links with another character than `_`
Can't a single `-` be used there?

**Comment by SMillerDev** [comment]
This was meant to make a distinct difference between objects, which are in the following style parent-object-child in URLs. It seems to be doing more bad then good however and function > readability.
