### ISSUE TITLE
Add this package to packagist.com

### ISSUE THREAD

**Issue by jrszapata** [SMillerDev/phpdraft#28]
It would be awesome if this package can be install using composer. But I don't see any composer.json file in the root of this repository. @SMillerDev are you intending to add this package to <https://packagist.org> in the near future?

**Comment by SMillerDev** [comment]
I personally don't use composer but feel free to send a PR. 

Regards, 
Sean Molenaar


On Wednesday, November 9, 2016 at 22:01 Stanley Zapata <notifications@github.com> wrote:

It would be awesome if this package can be install using composer. But I don't see any composer.json file in the root of this repository. @SMillerDev are you intending to add this package to https://packagist.org in the near future?

**Comment by SMillerDev** [comment]
You can refer to 4c9f5a0f3f402b76f27a5c9546125685e14d5bde for some basic info I put in a composer.json

Not really sure how to distribute phar files through packagist though

**Comment by jrszapata** [comment]
@SMillerDev thanks! You are almost done. Now that you added a _package.json_ there is no need to change or add files to your repo anymore. You just have to:

1. Merge the temp branch (the one with the composer.json file) to the master. Packagist looks for the _package.json_ file in the master branch.
2. Add the repo to packagist by going to <http://packagist.com>, signing in with your Github account and then in the [Submit](https://packagist.org/packages/submit) secction, add the link of your repo. 

That's it. 

Then if you want to allow packagist.com to autoupdate when any changes happend to your repo, which I recommend,  follow this simple steps (extracted from their [website](https://packagist.org/about#how-to-update-packages)):

1.     Go to your GitHub repository
2.     Click the "Settings" button
3.     Click "Integrations & services"
4.     Add a "Packagist" service, and configure it with your [API token](https://packagist.org/profile/), plus your Packagist username
5.     Check the "Active" box and submit the form

**Comment by SMillerDev** [comment]
Reading up on packagist, that wouldn't distribute the tool though right?
I mean, I have no objections distributing the source like this but it seems rather pointless.

**Comment by SMillerDev** [comment]
Should be done
