### ISSUE TITLE
Wrong separator used in example URLs for multiple variable URL parameters

### ISSUE THREAD

**Issue by pprkut** [SMillerDev/phpdraft#42]
When defining a resource with multiple variable params like
```
/resource/{id,version}
```
The generated URL would look like
```
https://www.example.com/resource/id,version
```
rather than
```
https://www.example.com/resource/id/version
```

**Comment by SMillerDev** [comment]
That's correct according to the rfc it's using/implementing https://tools.ietf.org/html/rfc6570

**Comment by pprkut** [comment]
Fair enough, but then how do I get it to use a slash in such a use case?
`/resource/{/id,version}` just gives me an error

**Comment by SMillerDev** [comment]
Why not `/resource/{id}/{version}`? 
On Monday, September 4, 2017 at 17:41 Heinz Wiesinger <notifications@github.com> wrote:

Fair enough, but then how do I get it to use a slash in such a use case?
/resource/{/id,version} just gives me an error

**Comment by pprkut** [comment]
Right. That works. Nevermind then.
