### ISSUE TITLE
More navigation with URL fragment

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#5]
It would be nice add some more ids to be able to navigate and link more easily to the apidoc
apidoc.url#people/get could scroll directly to the people/get part of the apidoc

**Comment by SMillerDev** [comment]
You mean like the links used in the navigationbar to the left?
doc.html#update-database
is a link to the update group > database call

**Comment by tardypad** [comment]
Ok it's fine I see now the `"name"` attribute there around (I was looking for `"id"`...)
Can we maybe make if like `"update/database"` instead of `"update-database"` when it's a request call?
Low prio though I guess
