### ISSUE TITLE
Remove JSON schema

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#6]
The JSON schema generated is quite primitive and probably not really useful
Probably best removed from the output

**Comment by SMillerDev** [comment]
I'd happily hide it or make it a parser argument but I'm gutting functionality :-1:

**Comment by tardypad** [comment]
The auto-generated schemas don't do anything with the arrays definition.
It just reports `"type": "array"` without describing the items definition... so this is kind of useless.
