### ISSUE TITLE
phar failed: 'No drafter available '

### ISSUE THREAD

**Issue by Grummfy** [SMillerDev/phpdraft#61]
Hello,
```
./phpdraft-1.13.3.phar -f path/to/api-file.md 
```
When I try to run the phar (version 1.13.3) I got the following error : "No drafter available"

**Comment by tardypad** [comment]
You need to install `drafter`.
This is a dependency as defined in the README.

**Comment by SMillerDev** [comment]
The other option is specifically defining that phpdraft can use the hosted version of drafter by specifying the `-o` option.

**Comment by Grummfy** [comment]
Well in the readme the dependencies information are very low. When you try a tool to compare them, you just want it works... Perhaps make dependency a bit higher or add a quick note to check the dependencies?

thanks for the help

**Comment by SMillerDev** [comment]
Moved the dependency information to the top. Thanks!
