### ISSUE TITLE
support drafter in docker

### ISSUE THREAD

**Issue by Grummfy** [SMillerDev/phpdraft#62]
Hello,
It could be cool to add the support for drafter in a docker version.

**Comment by SMillerDev** [comment]
But why

**Comment by Grummfy** [comment]
because I don't whant to compile and install an extra software on my machine, because it's faster to deploy to everybody instead of each compile it

**Comment by SMillerDev** [comment]
Wouldn't it be better to use the online mode then? I'm fine with allowing users to specify where phpdraft should look for docker, but I'm not really seeing the use case.

**Comment by Grummfy** [comment]
Well online, mean you give potential private information. That's all. ;)
But I can understand that's extra work

**Comment by SMillerDev** [comment]
Since I don't have a docker based setup, what does running drafter in docker look like? If it's just a different command location I might be able add it with relative ease.

**Comment by Grummfy** [comment]
```shell
docker run -it --rm -v $PWD:/doc -w /doc apiaryio/drafter drafter
docker run -it --rm -v $PWD:/doc -w /doc apiaryio/drafter:v3.2.2 drafter -h
```

* $PWD si the current path (the idea is to make the current directory available in the docker to make the file available
* I "mount" the files in the path /doc inside the docker
* here I give two example, one without docker tags and the other with the docker tags v3.2.2 (tags are available there https://hub.docker.com/r/apiaryio/drafter/tags/ )

if you have a project like this:
```
_ docs
|_ api
   |_ file1.apib
```
if you run the docker command from the root, the files available will be on the path /doc/docs/api/file1.apib
