### ISSUE TITLE
Can't get rendering to work

### ISSUE THREAD

**Issue by kschroeer** [SMillerDev/phpdraft#75]
I can't get the tool to run for my api-blueprint file. I only execute:

    ./phpdraft -f myfile.apib > myfile.html

I'm getting a large bunch of errors.

This is my file:
```apib
    FORMAT: 1A
    HOST: http://127.0.0.1/

    # Hello API

    A simple API demo

    # Group Verify

    ## POST /api/rest/verify

    Verify login data.

    ### Errors

    Errors returned by this service:

    <dl>
    <dt>1</dt>
    <dd>Login and password don't match</dd>
    <dt>2</dt>
    <dd>Username is unknown</dd>
    </dl>

    + Request (application/json)

        + Attributes (object)

            + `user`: `me` (string, required) - user name
            + `password`: `test` (string, required) - password

    + Response 200 (application/hal+json)

        + Attributes (object)

            + `success` (enum[number]) - value for request
                + Members
                    + 0
                    + 1
            + `error` (enum[number]) - error number in case of unsuccessful request
                + Members
                    + 1
                    + 2
            + `_links` (object)
                + `self` (object)
                    + `href`: `/api/rest/verify` (string)
```

**Comment by SMillerDev** [comment]
What is the output of `drafter -v`?

**Comment by kschroeer** [comment]
It's "v4.0.0".

**Comment by SMillerDev** [comment]
I'm still in the process of supporting that, it's fairly new. I already found a bug with it using your example and I'm going to try and release a fix for it in the next couple of hours.

**Comment by kschroeer** [comment]
Thanks in advance!

**Comment by SMillerDev** [comment]
https://github.com/SMillerDev/phpdraft/tree/1.15.2 should fix the first errors you were having. Some values still might not show up though.

**Comment by kschroeer** [comment]
Now there are no more errors. You can work well with the new version. Thanks a lot!

What I still miss is the representation of enumerations and embedded HTML code.  
But what I think would be even more important is that objects are also displayed (data structures), as they are very common.

I'll post an example:

```
FORMAT: 1A
HOST: localhost

# Sample API

This text gives some general information.

# Data Structures
## Counter

+ `name`: `example` (string) - name of the counter
+ `value`: `676` (number) - hash value

# Group GetCounter
## GET /api/rest/getcounter{?user_id,counter}

With this method it is possible to get the actual counter stored for a user.

### Errors

Errors returned by this service:

<dl>
    <dt>1</dt>
    <dd>Invalid user</dd>
    <dt>2</dt>
    <dd>No counter specified</dd>
</dl>

+ Parameters

    + `user_id`: `67` (number, required) - user ID
    + `counter`: `example` (string, optional) - separated by commas

+ Response 200 (application/hal+json)

    + Attributes (object)

        + `counter` (array[Counter]) - array of key-value-pairs
        + `success` (enum[number]) - value for request
            + Members
                + 0
                + 1
        + `error` (enum[number]) - error number in case of unsuccessful request
            + Members
                + 1
                + 2
```

**Comment by SMillerDev** [comment]
So, there is actually support for all of this. But drafter 4 (released a week or so ago) introduced a completely new way to represent all this information. So converting it will take some time. If you manage to get a hold of drafter 3.x you can check how objects are rendered.

**Comment by kschroeer** [comment]
I've downgraded Drafter to version 3.2.7 and now everything is fine.  
I would close this issue as the problems discussed here are solved.

I'm looking forward to the support of Drafter 4 and please do not forget to include embedded HTML markup as well.
