### ISSUE TITLE
Collapsible button is hard to find and reach

### ISSUE THREAD

**Issue by tardypad** [SMillerDev/phpdraft#9]
Probably it would be better if the collapsible button be on the left part
It seems more easy to find first and more accessible there

**Comment by pprkut** [comment]
Why have those buttons in the first place? It would be way better if clicking on the entire row would toggle IMHO

**Comment by SMillerDev** [comment]
I agree with @pprkut and that was what it was meant for once upon a time. Just never made it into the release.
